#define TAGIDENT 1
#define GTHAN 2
#define IDENT 3
#define ENDTAGHEAD 4
#define NUMBER 5
#define PLUS 6
#define MINUS 7
#define MULT 8 
#define DIVIDE 9 
#define MODULO 10 
#define EXP 11 
#define LPAREN 12
#define RPAREN 13
#define EQUALS 14
#define LTHAN 15
#define COLON 16
#define COMMA 17 
#define SCOLON 18 
#define PERIOD 19 
#define QUOTE 20 
#define DQUOTE 21 
#define OTHER 22 
#define END_OF_FILE 23
#define BFNUM 24
#define LBRACKET 25
#define RBRACKET 26